[CBRD-23662] json-function: translate english manual to korean
CUBRID/cubrid-manual pull request #115
Opened 2020-05-14 05:47 UTC by byungwook-kim

http://jira.cubrid.org/browse/CBRD-23662

Translate english manual to korean for v10.2.
This is for a part of json-function:
**json_array, json_object, json_keys, json_depth, json_length,
json_valid, json_type, json_quote, json_unquote, json_pretty,
json_search, json_extract, json_contains_path, json_contains**

2020-05-14 07:20 UTC, hgryoo requested changes
translating of line 214 is omitted.

2020-05-14 07:39 UTC, hgryoo reviewed
please refer #57 and add json_fn.rst in sql/index.rst.
To avoid omitting changes, we should refer PRs of corresponding contents to be translated.

2020-05-15 03:00 UTC, hgryoo requested changes

2020-05-15 03:00 UTC, hgryoo commented on ko/sql/function/json_fn.rst
> +  - *json path/pointer*: :ref:`json-path` 과 :ref:`json-pointer`에 설명된 규칙을 따르는 스트링
스트링 -> 문자열

2020-05-15 03:00 UTC, hgryoo commented on ko/sql/function/json_fn.rst
> +지원되는 JSON 함수들은 다음 표와 같다:
지원하는

2020-05-15 03:00 UTC, hgryoo commented on ko/sql/function/json_fn.rst
> +JSON 함수
JSON 함수 소개

2020-05-15 03:00 UTC, hgryoo commented on ko/sql/function/json_fn.rst
> +  **JSON_LENGTH** 함수는 해당 json 경로에 있는 json 요소의 길이를 반환한다.
해당 json 경로에 -> 주어진 경로에

2020-05-15 03:00 UTC, hgryoo commented on ko/sql/function/json_fn.rst
> +  **JSON_TYPE** 함수는 스트링 인자인 *json_doc*의 타입을 반환한다.
스트링 => 문자열

2020-05-15 03:00 UTC, hgryoo commented on ko/sql/function/json_fn.rst
> +  **JSON_QUOTE** 함수는 문자열과 이스케이프된 특수 문자들을 쌍따옴표로 묶은 json_string을 결과로 반환한다.
쌍따옴표 -> 큰따옴표

2020-05-15 03:00 UTC, hgryoo commented on ko/sql/function/json_fn.rst
> +  json경로 인자가 누락된 경우, **JSON_SEARCH**는 루트 요소로 부터 탐색을 시작한다.
space omitted

2020-05-15 03:00 UTC, hgryoo commented on ko/sql/function/json_fn.rst
> +  josn path가 **NULL**이거나 유효하지 않은 경우 혹은 *json_doc* 인자가 유효하지 않은 경우 에러가 반환된다.
josn path -> json 경로 (typo and not translated)

2020-05-15 03:00 UTC, hgryoo commented on ko/sql/function/json_fn.rst
> +  와일드카드를 사용하지 않고 json 경로에서 하나의 요소만 발견된 경우 하나의 json 요소만 반환되며, 그렇지 않은 경우 발견된 json요소는 json 배열에 래핑된다.
json 요소 (space omitted)

2020-05-15 03:00 UTC, hgryoo commented on ko/sql/function/json_fn.rst
> +  와일드카드를 사용하지 않고 json 경로에서 하나의 요소만 발견된 경우 하나의 json 요소만 반환되며, 그렇지 않은 경우 발견된 json요소는 json 배열에 래핑된다.
래핑된다
I think we need to translate it.

2020-05-15 03:00 UTC, hgryoo commented on ko/sql/function/json_fn.rst
> +   **JSON_UNQUOTE**의 별명 (json_doc->json 경로). 본 연산자는 컬럼인 *json_doc* 인자에만 적용 할 수 있다.
별명 -> 별칭

2020-05-15 03:00 UTC, hgryoo commented on ko/sql/function/json_fn.rst
> +  다음 재귀 규칙이 충족되는 경우 json 요소에 다른 json 요소가 포함된다.
please add "다음과 같이"

2020-05-15 03:00 UTC, hgryoo commented on ko/sql/function/json_fn.rst
> +주로 아래와 같이 다양한 유형의 입력 방식을 가지고 있다.
다양한 -> 몇 가지
입력 방식 -> 입력 인수

2020-05-15 03:00 UTC, hgryoo commented on ko/sql/function/json_fn.rst
> +  JSON 함수 스트링 인자의 코드셋은 UTF8을 기준으로 한다. 다른 코드셋의 입력 문자열은 UTF8로 변환된다.
스트링 -> 문자열

2020-05-15 03:35 UTC, shparkcubrid commented on ko/sql/function/json_fn.rst
> +다음의 표는 입력 인자로 받아들이는 *json_doc* 와 *val*의 차이를 보여주고 있다:
how about it ?  '다음의 표는 입력 인자를 받아들이는데 있어서 *json_doc...... '

2020-05-15 03:37 UTC, shparkcubrid commented on ko/sql/function/json_fn.rst
> +  **JSON_ARRAY** 함수는 해당 값들(val, val2, ..)을 가진 리스트(텅빈 리스트도 가능)가 포함된 배열을 반환한다.
배열 -> json 배열

2020-05-15 03:39 UTC, shparkcubrid commented on ko/sql/function/json_fn.rst
> +  **JSON_OBJECT** 함수는 해당 키/값(key, val1, key, val2,...)쌍을 가진 리스트(텅빈 리스트도 가능)가 포함된 객체를 반환한다.
객체 -> json 객체

2020-05-15 03:40 UTC, hgryoo commented on ko/sql/function/json_fn.rst
> +  와일드카드를 사용하지 않고 json 경로에서 하나의 요소만 발견된 경우 하나의 json 요소만 반환되며, 그렇지 않은 경우 발견된 json요소는 json 배열에 래핑된다.
json요소 -> json 요소

2020-05-15 03:47 UTC, shparkcubrid commented on ko/sql/function/json_fn.rst
> +  **JSON_KEYS** 함수는 해당 패스로 주어진 json 객체의 모든 키값을 가진 배열을 반환한다.
배열-> json 배열

2020-05-15 05:08 UTC, byungwook-kim commented on ko/sql/function/json_fn.rst
> +다음의 표는 입력 인자로 받아들이는 *json_doc* 와 *val*의 차이를 보여주고 있다:
"입력인자를 처리하는데 있어서" 라는 표현이 더 자연스러워 보입니다.

2020-05-18 08:00 UTC, shparkcubrid approved these changes

2020-05-18 23:56 UTC, hgryoo commented on ko/sql/function/json_fn.rst
> +  json 경로 인자가 제공되지 않은 경우 *doc2*가 *doc1*의 루트 json 요소에 포함되는지 여부를 리턴한다.
json 경로 인자를 입력하지 않는 경우

2020-05-18 23:57 UTC, hgryoo commented on ko/sql/function/json_fn.rst
> +  json 경로 인자가 제공되지 않은 경우 *doc2*가 *doc1*의 루트 json 요소에 포함되는지 여부를 리턴한다.
리턴한다 -> 반환한다

2020-05-19 00:08 UTC, hgryoo approved these changes

2020-05-19 00:13 UTC, byungwook-kim commented on ko/sql/function/json_fn.rst
> +  json 경로 인자가 제공되지 않은 경우 *doc2*가 *doc1*의 루트 json 요소에 포함되는지 여부를 리턴한다.
good point.

2020-05-19 00:21 UTC, merged