[CBRD-23662] json-function: translate english manual to korean
CUBRID/cubrid-manual pull request #116
Opened 2020-05-19 08:23 UTC by shparkcubrid

http://jira.cubrid.org/browse/CBRD-23662

Translate english manual to korean for v10.2.
This is for a part of json-function:
JSON_MERGE_PATCH, JSON_MERGE_PRESERVE, JSON_MERGE, JSON_ARRAY_APPEND
JSON_ARRAY_INSERT, JSON_INSERT, JSON_SET, JSON_REPLACE, JSON_REMOVE, JSON_TABLE

2020-05-19 23:37 UTC, byungwook-kim commented on ko/sql/function/json_fn.rst
리턴한다 -> 반환한다
인수 -> 인자
재귀 적 -> 재귀적
개채 -> 객체
멤버일때 -> 멤버일 때
결과가된다 -> 결과가 된다

2020-05-19 23:44 UTC, byungwook-kim commented on ko/sql/function/json_fn.rst
> +  - 두 개의 비 배열 (스칼라 / 오브젝트) json 요소가 병합되고 최대 하나가 json 객체 인 경우 결과는 두 개의 json 요소를 포함하는 배열이다.
그 중 하나가 json 객체인 경우

2020-05-19 23:52 UTC, byungwook-kim commented on ko/sql/function/json_fn.rst
> +  - 두 개의 json 객체가 병합되면 다른 json 객체와 비교해 없는 모든 멤버가 유지된다. 일치하는 키의 경우 규칙을 재귀 적으로 적용하여 값이 항상 병합된다.
두 개의 json 객체가 병합될 때, 상대 json 객체에 해당 쌍(pair)이 없는 경우, 모든 쌍이 유지된다.

2020-05-19 23:53 UTC, byungwook-kim commented on ko/sql/function/json_fn.rst
병합되고이 결과는 -> 병합되고 이 결과는

2020-05-19 23:55 UTC, byungwook-kim commented on ko/sql/function/json_fn.rst
> +** JSON_MERGE_PATCH **와 달리 ** JSON_MERGE_PRESERVE **는 병합하는 동안 첫 번째 인수의 요소를 삭제 및 수정하지 않고 함께 수집한다.
합쳐서 가져온다

2020-05-19 23:55 UTC, byungwook-kim commented on ko/sql/function/json_fn.rst
> +  병합 작업은 두 개 이상의 인수가있을 때 연속적으로 실행된다. 처음 두 인수를 병합 한 결과는 세 번째와 병합되고이 결과는 네 번째와 병합된다.
병합되고이 결과는 -> 병합되고 이 결과는

2020-05-19 23:56 UTC, byungwook-kim commented on ko/sql/function/json_fn.rst
> +첫 번째 인수가 객체가 아니고 두 번째 인수가 객체 인 경우 병합에 대한 예외. 빈 개체와 두 번째 개체 인수간에 병합 작업이 수행된다.
리턴한다 -> 반환한다
인수 -> 인자
재귀 적 -> 재귀적
개채 -> 객체
멤버일때 -> 멤버일 때
결과가된다 -> 결과가 된다

2020-05-19 23:57 UTC, byungwook-kim commented on ko/sql/function/json_fn.rst
> +  (* json path *, * json_val *) 은 왼쪽에서 오른쪽으로 하나씩 평가된다. 한 쌍을 평가하여 작성된 문서는 다음 쌍이 평가되는 새로운 값이된다.
값이 된다

2020-05-20 00:00 UTC, byungwook-kim commented on ko/sql/function/json_fn.rst
> +  (* json path *, * json_val *) 은 왼쪽에서 오른쪽으로 하나씩 평가된다. 한 쌍을 평가하여 작성된 문서는 다음 쌍이 평가되는 새로운 값이된다.
다른 쌍이 평가되는 -> 다른 쌍을 평가하는

2020-05-20 00:01 UTC, byungwook-kim commented on ko/sql/function/json_fn.rst
> +  - json 경로가 json_array의 요소를 지정하면 * json_val *이 지정된 색인에 삽입되어 다음 요소를 오른쪽으로 이동한다.
이동한다 -> 이동 시킨다

2020-05-20 00:01 UTC, byungwook-kim commented on ko/sql/function/json_fn.rst
> +  - json 경로가 배열 끝의 다음을 가리키는 경우, 배열의 끝부터 지정된 색인에 삽입 될 때까지 null로채워진다. 그리고 json_val이 지정된 색인에 삽입된다.
null로채워진다 -> null로 채워진다

2020-05-20 00:07 UTC, byungwook-kim commented on ko/sql/function/json_fn.rst
> +  - json 경로가 * json_doc * 내에 존재하지 않는 경우, json 경로의 마지막 토큰은 배열 인덱스이고 마지막 토큰을 제외한 json 경로는 * json_doc * 내의 요소를 지정했을 것이다. 마지막 토큰을 제외한 json 경로로 찾은 요소는 단일 요소 json 배열로 대체되고 ** JSON_ARRAY_INSERT ** 작업은 원래 js
마지막 토큰을 제외한 -> 마지막 배열 인덱스 토큰이 없는

2020-05-20 00:09 UTC, byungwook-kim commented on ko/sql/function/json_fn.rst
> +  인수가 유효하지 않거나 * json_path *가 * json_doc * 내부의 배열의 장소를 가르키지 않으면 오류가 발생한다.
가르키지 -> 가리키지

2020-05-20 00:13 UTC, byungwook-kim commented on ko/sql/function/json_fn.rst
> +  - 기존 json 객체의 존재하지 않는 객체 멤버이다. key가 json 경로의 마지막 요소이고 값이 * json_val * 인 (* key *, * value *)이 json 오브젝트에 추가된다.
기존 json 객체의 존재하지 않는 객체 멤버이다 -> 기존 json 객체에 존재하지 않는 객체 멤버
key가 --> 키(key)가

2020-05-20 00:14 UTC, byungwook-kim commented on ko/sql/function/json_fn.rst
> +  json 경로가 * json_doc * 내부에서 아래의 json 값 중 하나를 가르키면 * json_val *이 삽입된다.
가르키면 -> 가르치면 (or 지정하면)

2020-05-20 00:15 UTC, byungwook-kim commented on ko/sql/function/json_fn.rst
> +  - 기존 json 객체의 존재하지 않는 객체 멤버이다. (* key *, * value *) 이 json 경로에서 추론 된 키와 * json_val * 값으로 json 객체에 추가된다.
기존 json 객체의 존재하지 않는 객체 멤버이다 -> 기존 json 객체에 존재하지 않는 객체 멤버

2020-05-20 00:17 UTC, byungwook-kim commented on ko/sql/function/json_fn.rst
> + ** JSON_REPLACE ** 함수는 첫 번째 인수의 수정 된 사본을 리턴한다. 주어진 각 <* json path *, * json_val *> 에 대해 해당 경로에 다른 값이있는 경우에만 함수가 값을 대체한다.
수정 된 -> 수정된
값이있는 -> 값이 있는
함수가 값을 대체한다 -> 값을 대체한다

2020-05-20 00:19 UTC, byungwook-kim commented on ko/sql/function/json_fn.rst
> +* json_doc * 안에 * json path *`가 없으면 대체가 수행되지 않는다.
대체가 -> 대체(replace) 동작이

2020-05-20 00:20 UTC, byungwook-kim commented on ko/sql/function/json_fn.rst
> + 인수가 유효하지 않거나 경로가 루트를 가리 키거나 경로가없는 경우 오류가 발생한다.
가리 키거나 -> 가리키거나 (or 지정하거나)
경로가없는 -> 경로가 없는

2020-05-20 00:22 UTC, byungwook-kim commented on ko/sql/function/json_fn.rst
> +변환은 예를 들면 JSON_ARRAY 요소를 확장함으로써, 하나의 행 또는 복수의 열을 생성한다.
쿼리 할 수있는 -> 질의(query)할 수 있는
테이블 유사 -> 유사 테이블
용이하게 한다 -> 용이하게 해준다
복수의 열 -> 복수의 행

2020-05-20 00:23 UTC, byungwook-kim commented on ko/sql/function/json_fn.rst
> +* json path *는 유효한 경로 여야하며 ** COLUMNS ** 절에서 평가할 json 데이터를 추출하는 데 사용된다.
경로 여야하며 -> 경로 이어야 하며

2020-05-20 00:24 UTC, byungwook-kim commented on ko/sql/function/json_fn.rst
> +- * name * ** FOR ORDINALITY ** :이 유형은 ** COLUMNS ** 절 내에서 행 번호를 추적한다. 열 유형은 ** INTEGER **이다.
행 번호 -> 열 번호

2020-05-20 00:25 UTC, byungwook-kim commented on ko/sql/function/json_fn.rst
> +  경로가 존재하지 않으면 json 값은 ** on empty ** 절을 트리거한다. 추출 된 json 값이 대상 유형에 강제되지 않으면 ** on error ** 절이 트리거된다.
절을 트리거한다 -> 절이 실행된다

2020-05-20 00:28 UTC, byungwook-kim commented on ko/sql/function/json_fn.rst
> +세 번째 멤버의 값인 6은 배열로 취급 될 수 없으므로 중첩 된 열로 처리 할 수 없다. 중첩 된 열은 ** NULL ** 값을 생성한다.
취급 될 -> 취급될

2020-05-20 00:30 UTC, hgryoo requested changes

2020-05-20 00:30 UTC, hgryoo commented on ko/sql/function/json_fn.rst
> +** JSON_MERGE_PATCH ** 함수는 둘 이상의 json 문서를 병합하고 병합 된 결과 json을 리턴한다. ** JSON_MERGE_PATCH **는 병합 충돌시 두 번째 인수를 사용하는  점에서 ** JSON_MERGE_PRESERVE **와 다르다.
리턴한다 -> 반환한다

2020-05-20 00:30 UTC, hgryoo commented on ko/sql/function/json_fn.rst
> +** FOR ORDINALITY ** * nested_ord * 열은 형제 열에 의해 처리되는 요소 수의 카운터 역할도 한다. 중첩 된 ** FOR ORDINALITY ** 열은 각 처리 일괄 처리가 완료된 후 재설정된다.
형제 열 (sibling columns)와 같이 병기하는 것이 좋을 것 같습니다.

2020-05-20 00:30 UTC, hgryoo commented on ko/sql/function/json_fn.rst
> +  두 json 문서의 병합은 다음 규칙에 따라 재귀 적으로 수행된다:
재귀 적으로 -> 재귀적으로

2020-05-20 00:31 UTC, hgryoo commented on ko/sql/function/json_fn.rst
> +** FOR ORDINALITY ** * nested_ord * 열은 형제 열에 의해 처리되는 요소 수의 카운터 역할도 한다. 중첩 된 ** FOR ORDINALITY ** 열은 각 처리 일괄 처리가 완료된 후 재설정된다.
"각 처리 일괄 처리가 완료된 후 재설정된다." 어색한 표현입니다.

2020-05-20 07:30 UTC, hgryoo requested changes

2020-05-20 07:30 UTC, hgryoo commented on ko/sql/function/json_fn.rst
> +병합 작업은 두 개 이상의 인수가있을 때 연속적으로 실행된다. 처음 두 인수를 병합 한 결과는 세 번째와 병합되고 이 결과는 네 번째와 병합된다.
인수가있을 때 -> 인수가 있을 때
병합 한 결과는 -> 병합한 결과는

2020-05-20 07:30 UTC, hgryoo commented on ko/sql/function/json_fn.rst
> +  - 두 번째 개체와 동일한 키를 가진 null이 아닌 첫 번째 개체의 멤버. 두 객체 모두에 나타나는 동일한 키 멤버일때 두 번째 객체의 멤버 값이 null이면 무시된다. 이 두개의 값은 첫 번째 및 두 번째 객체의 멤버 값에 대해 수행된 병합의 결과가된다.
이 두개의 값은 -> 이 두 개의 값은

2020-05-20 07:30 UTC, hgryoo commented on ko/sql/function/json_fn.rst
> +  ** JSON_ARRAY_APPEND ** 함수는 첫 번째 인수의 수정 된 사본을 리턴한다. 주어진 각 <* json path *, * json_val *> 에 대해 함수는 해당 경로로 지정된 json 배열에 값을 추가한다.
리턴한다->반환한다

2020-06-02 05:53 UTC, hgryoo approved these changes

2020-06-02 06:44 UTC, beyondykk9 approved these changes

2020-06-03 05:31 UTC, merged