[CUBRIDMAN-14] [kr] Statement and result cache to improve performance for frequently repeated queries
CUBRID/cubrid-manual pull request #258
Opened 2020-12-17 09:33 UTC by byungwook-kim

http://jira.cubrid.org/browse/CUBRIDMAN-14

The result cache as known query cache in previous version is refactored in version 11.

The configurable parameter is 3 as below but the they are enabled newly.

QUERY_CACHE_MODE
MAX_QUERY_CACHE_ENTRIES
MAX_QUERY_CACHE_PAGES
The above parameters affect the following sections:

system parameter related
query processing related
csql related (for query cache information display)
etc.

This is Korean version.

2020-12-17 09:52 UTC, hgryoo requested changes

2020-12-17 09:52 UTC, hgryoo commented on ko/admin/config.rst
> +Query Cache-Related Parameters
please translate in Korean.

2020-12-17 09:52 UTC, hgryoo commented on ko/admin/config.rst
> +| Parameter Name                | Type   | Default  | Min      | Max      |
please translate in Korean.

2020-12-17 09:52 UTC, hgryoo commented on ko/sql/tuning.rst
> +* 저장 프로 시저 또는 저장 함수가 포함된 경우
```suggestion
* 저장 프로 시저 또는 저장 함수가 포함된 경우.
```

2020-12-17 09:52 UTC, hgryoo commented on ko/sql/tuning.rst
> +* 아래와 같이 질의에 시스템 시간 또는 날짜 관련 속성이 포함된 경우
```suggestion
* 아래와 같이 질의에 시스템 시간 또는 날짜 관련 속성이 포함된 경우.
```

2020-12-17 09:52 UTC, hgryoo commented on ko/admin/config.rst
> +    다음 예는 최대 4000 페이지의 결과를 캐시하는 것을 보여주고 있다 ::
```suggestion
    다음 예는 최대 4000 페이지의 결과를 캐시하는 것을 보여주고 있다. ::
```

2020-12-18 01:25 UTC, hgryoo commented on ko/admin/config.rst
> +    **max_query_cache_entries** 는 최대 캐시할 수 있는 질의 개수에 대한 설정 값이다. 이 파라미터 값이 1이상으로 설정되면 설정된 수 만큼의 질의가 캐시된다.
format; one more newline like query_cache_size_in_pages below

2020-12-18 01:25 UTC, hgryoo commented on ko/admin/config.rst
> +| Parameter Name              | 타입   | 기본값  |  최소값   | 최대값  |
Parameter Name -> 파라미터 이름

2020-12-18 02:33 UTC, shparkcubrid commented on ko/admin/config.rst
> +다음은 질의 결과에 대한 캐시 기능과 관련된 파라미터로 각 파라미터의 타입과 설정 가능한 갑의 범위는 다음과 같다.
```suggestion
다음은 질의 결과에 대한 캐시 기능과 관련된 파라미터로 각 파라미터의 타입과 설정 가능한 값의 범위는 다음과 같다.
```

2020-12-18 02:44 UTC, shparkcubrid commented on ko/sql/tuning.rst
> +힌트가 설정되고 새 SELECT 질의가 처리 될 때 질의가 캐시에서 발견되면 쿼리 캐시를 사용한다. 동일한 데이터베이스에서 동일한 질의 텍스트와 동일한 바인딩 값을 사용하는 경우 질의는 동일한 것으로 간주된다. 캐시 된 질의를 찾을 수없는 경우 질의가 처리된 다음 결과와 함께 캐시가 생성된다. 질의가 캐시에서 발견되면 캐시된 영역에서 결과를 가져온다. C
```suggestion
힌트가 설정되고 새 SELECT 질의가 처리될 때 질의가 캐시에서 발견되면 쿼리 캐시를 사용한다. 동일한 데이터베이스에서 동일한 질의 텍스트와 동일한 바인딩 값을 사용하는 경우 질의는 동일한 것으로 간주된다. 캐시 된 질의를 찾을 수 없는 경우 질의가 처리된 다음 결과와 함께 캐시가 생성된다. 질의가 캐시에서 발견되면 캐시된 영역에서 결과를 가져온다. CSQL에서는 아래 예제와 같이 COUNT 함수를 사용하여 질의를 반복적으로 실행할 때 개선된 성능을 쉽게 측정 할 수 있다. 첫번째 질의에 대한 결과는 캐시가 되어 있지 않아서 느리지만, 두 번째 질의의 결과는 캐시된 영역에서 가져오므로 응답 시간이 이전 질의보다 훨씬 빠르다. ::
```

2020-12-18 05:45 UTC, shparkcubrid approved these changes

2020-12-18 05:55 UTC, hgryoo approved these changes

2020-12-18 05:55 UTC, merged